import React from 'react';
import Head from 'next/head';
import Navbar from './Navbar';

const layout = ({title, children}) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        <div className='bg-gray-300'> 
            {children}
        </div>
    </div>
  )
}

export default layout;
